# 项目名称
name: Build&Push

on:
  workflow_dispatch:
  # 代码推送到master分支触发
  push:
    branches: [ "main" ]

jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - name: Get the content of algolia.json as config
      id: algolia_config
      run: echo "config=$(cat crawlerConfig.json | jq -r tostring)" >> $GITHUB_OUTPUT
    - name: Push indices to Algolia
      uses: signcl/docsearch-scraper-action@master
      env:
        APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
        API_KEY: ${{ secrets.API_KEY }}
        CONFIG: ${{ steps.algolia_config.outputs.config }}
    - name: Install dependencies
      run: npm i -g pnpm
    - run: pnpm install
    - run: pnpm run docs:build
    - run: zip -r data.zip .vitepress/dist/
    - run: ls -l
   
    # 上传部署
    - name: scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.YUXUAN_MAIN_SERVER_IP }}
        user: ${{ secrets.YUXUAN_MAIN_SERVER_USER }}
        pass: ${{ secrets.YUXUAN_MAIN_SERVER_PASS }}
        scp: |
          ./data.zip => /mnt/project/web/docs
        last_ssh: |
          echo $LASTSSH 
          cd /mnt/project/web/docs
          unzip -o data.zip
          rm data.zip
